<?php
/**
 * FlightBookingBoundsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightBookingBoundsTest Class Doc Comment
 *
 * @category    Class
 * @description FlightBookingBounds
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightBookingBoundsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightBookingBounds"
     */
    public function testFlightBookingBounds()
    {
    }

    /**
     * Test attribute "arrival_date"
     */
    public function testPropertyArrivalDate()
    {
    }

    /**
     * Test attribute "arrival_location"
     */
    public function testPropertyArrivalLocation()
    {
    }

    /**
     * Test attribute "arrival_time"
     */
    public function testPropertyArrivalTime()
    {
    }

    /**
     * Test attribute "booking_class"
     */
    public function testPropertyBookingClass()
    {
    }

    /**
     * Test attribute "departure_date"
     */
    public function testPropertyDepartureDate()
    {
    }

    /**
     * Test attribute "departure_location"
     */
    public function testPropertyDepartureLocation()
    {
    }

    /**
     * Test attribute "departure_time"
     */
    public function testPropertyDepartureTime()
    {
    }

    /**
     * Test attribute "destination"
     */
    public function testPropertyDestination()
    {
    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {
    }

    /**
     * Test attribute "segments"
     */
    public function testPropertySegments()
    {
    }
}
