<?php
/**
 * FlightAvailabilityResponseBoundTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightAvailabilityResponseBoundTest Class Doc Comment
 *
 * @category    Class
 * @description FlightAvailabilityResponseBound
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightAvailabilityResponseBoundTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightAvailabilityResponseBound"
     */
    public function testFlightAvailabilityResponseBound()
    {
    }

    /**
     * Test attribute "eft"
     */
    public function testPropertyEft()
    {
    }

    /**
     * Test attribute "airlines"
     */
    public function testPropertyAirlines()
    {
    }

    /**
     * Test attribute "arrival"
     */
    public function testPropertyArrival()
    {
    }

    /**
     * Test attribute "day_difference"
     */
    public function testPropertyDayDifference()
    {
    }

    /**
     * Test attribute "departure"
     */
    public function testPropertyDeparture()
    {
    }

    /**
     * Test attribute "flight_duration"
     */
    public function testPropertyFlightDuration()
    {
    }

    /**
     * Test attribute "flight_id"
     */
    public function testPropertyFlightId()
    {
    }

    /**
     * Test attribute "nb_stops"
     */
    public function testPropertyNbStops()
    {
    }

    /**
     * Test attribute "segments"
     */
    public function testPropertySegments()
    {
    }

    /**
     * Test attribute "stop_duration"
     */
    public function testPropertyStopDuration()
    {
    }

    /**
     * Test attribute "stopover_airports"
     */
    public function testPropertyStopoverAirports()
    {
    }
}
