<?php
/**
 * FlightFareTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightFareTest Class Doc Comment
 *
 * @category    Class
 * @description FlightFare
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightFareTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightFare"
     */
    public function testFlightFare()
    {
    }

    /**
     * Test attribute "allow_minor_single_passenger"
     */
    public function testPropertyAllowMinorSinglePassenger()
    {
    }

    /**
     * Test attribute "can_be_booked_onhold"
     */
    public function testPropertyCanBeBookedOnhold()
    {
    }

    /**
     * Test attribute "can_be_voided"
     */
    public function testPropertyCanBeVoided()
    {
    }

    /**
     * Test attribute "is_bookable"
     */
    public function testPropertyIsBookable()
    {
    }

    /**
     * Test attribute "pax_name_character_limit"
     */
    public function testPropertyPaxNameCharacterLimit()
    {
    }

    /**
     * Test attribute "pax_name_character_limit_inf"
     */
    public function testPropertyPaxNameCharacterLimitInf()
    {
    }
}
