<?php
/**
 * FlightDetailedPriceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightDetailedPriceTest Class Doc Comment
 *
 * @category    Class
 * @description FlightDetailedPrice
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightDetailedPriceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightDetailedPrice"
     */
    public function testFlightDetailedPrice()
    {
    }

    /**
     * Test attribute "adt_price"
     */
    public function testPropertyAdtPrice()
    {
    }

    /**
     * Test attribute "chd_price"
     */
    public function testPropertyChdPrice()
    {
    }

    /**
     * Test attribute "inf_price"
     */
    public function testPropertyInfPrice()
    {
    }

    /**
     * Test attribute "ins_price"
     */
    public function testPropertyInsPrice()
    {
    }

    /**
     * Test attribute "src_price"
     */
    public function testPropertySrcPrice()
    {
    }

    /**
     * Test attribute "yth_price"
     */
    public function testPropertyYthPrice()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "agency_fees"
     */
    public function testPropertyAgencyFees()
    {
    }

    /**
     * Test attribute "agency_fees_per_pax"
     */
    public function testPropertyAgencyFeesPerPax()
    {
    }

    /**
     * Test attribute "agency_markup"
     */
    public function testPropertyAgencyMarkup()
    {
    }

    /**
     * Test attribute "base_fare"
     */
    public function testPropertyBaseFare()
    {
    }

    /**
     * Test attribute "pax_number"
     */
    public function testPropertyPaxNumber()
    {
    }

    /**
     * Test attribute "platform_fees"
     */
    public function testPropertyPlatformFees()
    {
    }

    /**
     * Test attribute "platform_fees_per_pax"
     */
    public function testPropertyPlatformFeesPerPax()
    {
    }

    /**
     * Test attribute "platform_markup"
     */
    public function testPropertyPlatformMarkup()
    {
    }

    /**
     * Test attribute "service_amount_per_pax"
     */
    public function testPropertyServiceAmountPerPax()
    {
    }

    /**
     * Test attribute "service_fees"
     */
    public function testPropertyServiceFees()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "total_in_requested_currency"
     */
    public function testPropertyTotalInRequestedCurrency()
    {
    }

    /**
     * Test attribute "total_platform"
     */
    public function testPropertyTotalPlatform()
    {
    }

    /**
     * Test attribute "total_provider"
     */
    public function testPropertyTotalProvider()
    {
    }
}
