<?php
/**
 * FlightRecommendationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightRecommendationTest Class Doc Comment
 *
 * @category    Class
 * @description FlightRecommendation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightRecommendationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightRecommendation"
     */
    public function testFlightRecommendation()
    {
    }

    /**
     * Test attribute "baggage"
     */
    public function testPropertyBaggage()
    {
    }

    /**
     * Test attribute "booking_key"
     */
    public function testPropertyBookingKey()
    {
    }

    /**
     * Test attribute "fare_details"
     */
    public function testPropertyFareDetails()
    {
    }

    /**
     * Test attribute "flights"
     */
    public function testPropertyFlights()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "sub_recommendations"
     */
    public function testPropertySubRecommendations()
    {
    }

    /**
     * Test attribute "validating_carrier"
     */
    public function testPropertyValidatingCarrier()
    {
    }
}
