<?php
/**
 * FlightBookingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightBookingTest Class Doc Comment
 *
 * @category    Class
 * @description FlightBooking
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightBookingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightBooking"
     */
    public function testFlightBooking()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "airlines"
     */
    public function testPropertyAirlines()
    {
    }

    /**
     * Test attribute "booking_can_be_void"
     */
    public function testPropertyBookingCanBeVoid()
    {
    }

    /**
     * Test attribute "booking_class"
     */
    public function testPropertyBookingClass()
    {
    }

    /**
     * Test attribute "booking_date"
     */
    public function testPropertyBookingDate()
    {
    }

    /**
     * Test attribute "booking_need_exchange_documents"
     */
    public function testPropertyBookingNeedExchangeDocuments()
    {
    }

    /**
     * Test attribute "bounds"
     */
    public function testPropertyBounds()
    {
    }

    /**
     * Test attribute "canceled"
     */
    public function testPropertyCanceled()
    {
    }

    /**
     * Test attribute "confirmed"
     */
    public function testPropertyConfirmed()
    {
    }

    /**
     * Test attribute "could_not_retrieve_etickets"
     */
    public function testPropertyCouldNotRetrieveEtickets()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "destination"
     */
    public function testPropertyDestination()
    {
    }

    /**
     * Test attribute "etickets"
     */
    public function testPropertyEtickets()
    {
    }

    /**
     * Test attribute "history"
     */
    public function testPropertyHistory()
    {
    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {
    }

    /**
     * Test attribute "offline"
     */
    public function testPropertyOffline()
    {
    }

    /**
     * Test attribute "option_deadline"
     */
    public function testPropertyOptionDeadline()
    {
    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {
    }

    /**
     * Test attribute "pax_number"
     */
    public function testPropertyPaxNumber()
    {
    }

    /**
     * Test attribute "pending"
     */
    public function testPropertyPending()
    {
    }

    /**
     * Test attribute "pnr"
     */
    public function testPropertyPnr()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "provider"
     */
    public function testPropertyProvider()
    {
    }

    /**
     * Test attribute "queued"
     */
    public function testPropertyQueued()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "refund"
     */
    public function testPropertyRefund()
    {
    }

    /**
     * Test attribute "routing"
     */
    public function testPropertyRouting()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "ticketed"
     */
    public function testPropertyTicketed()
    {
    }

    /**
     * Test attribute "trip_type"
     */
    public function testPropertyTripType()
    {
    }

    /**
     * Test attribute "validating_carrier"
     */
    public function testPropertyValidatingCarrier()
    {
    }
}
