<?php
/**
 * HotelAvailabilityResponseHotelsRatesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HotelAvailabilityResponseHotelsRatesTest Class Doc Comment
 *
 * @category    Class
 * @description HotelAvailabilityResponseHotelsRates
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HotelAvailabilityResponseHotelsRatesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HotelAvailabilityResponseHotelsRates"
     */
    public function testHotelAvailabilityResponseHotelsRates()
    {
    }

    /**
     * Test attribute "board_name"
     */
    public function testPropertyBoardName()
    {
    }

    /**
     * Test attribute "board_code"
     */
    public function testPropertyBoardCode()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "rate_key"
     */
    public function testPropertyRateKey()
    {
    }

    /**
     * Test attribute "rate_comment"
     */
    public function testPropertyRateComment()
    {
    }

    /**
     * Test attribute "taxes"
     */
    public function testPropertyTaxes()
    {
    }

    /**
     * Test attribute "cancellation_policies"
     */
    public function testPropertyCancellationPolicies()
    {
    }
}
